services:
  bot:
    image: mrsalt3000/mylife3000:v1.0.2
    working_dir: /project
    volumes:
      - "../:/project"
    command: sh -c "python -m src.mylife3000" 
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

  postgres:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_mylife3000:/var/lib/postgresql/data
      - ../data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: |
        pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} &&
        psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c "SELECT 1 FROM conversations.dialogs LIMIT 1;"
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_mylife3000: